export const GET_NEXT_INVOICE_ID_QUERY = `
  SELECT MAX(CODFAC) AS maxid FROM F_FAC WHERE TIPFAC = ?
`;

export const CHECK_INVOICE_BY_REF_QUERY = `
  SELECT CODFAC, TIPFAC, REFFAC, TOTFAC, ESTFAC, FECFAC 
  FROM F_FAC 
  WHERE REFFAC = ?
`;

export const CHECK_INVOICE_BY_ID_QUERY = `
  SELECT CODFAC, TIPFAC, REFFAC, TOTFAC, ESTFAC, FECFAC 
  FROM F_FAC 
  WHERE TIPFAC = ? AND CODFAC = ?
`;

export const SELECT_INVOICES_HEADER_QUERY = `
  SELECT 
    TIPFAC, CODFAC, REFFAC, FECFAC, ESTFAC, ALMFAC, AGEFAC, CLIFAC,
    CNOFAC, CDOFAC, CPOFAC, CCPFAC, CPRFAC, TELFAC, CEMFAC, CPAFAC,
    PIVA1FAC, PIVA2FAC, PIVA3FAC, NET1FAC, IIVA1FAC, IPOR1FAC, TOTFAC
  FROM F_FAC
  ORDER BY FECFAC DESC, CODFAC DESC
`;

export const SELECT_INVOICE_LINES_QUERY = `
  SELECT 
    TIPLFA, CODLFA, POSLFA, ARTLFA, DESLFA, CANLFA, PRELFA, TOTLFA
  FROM F_LFA
  WHERE TIPLFA = ? AND CODLFA = ?
  ORDER BY POSLFA ASC
`;

export const INSERT_INVOICE_HEADER_QUERY = `
  INSERT INTO F_FAC (
    TIPFAC, CODFAC, REFFAC, FECFAC, ESTFAC, ALMFAC, AGEFAC, CLIFAC,
    CNOFAC, CDOFAC, CPOFAC, CCPFAC, CPRFAC, TELFAC, CEMFAC, CPAFAC,
    PIVA1FAC, PIVA2FAC, PIVA3FAC, IPOR1FAC, IIVA1FAC, NET1FAC, TOTFAC
  ) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?
  )
`;

export const INSERT_INVOICE_LINE_QUERY = `
  INSERT INTO F_LFA (
    TIPLFA, CODLFA, POSLFA, ARTLFA, DESLFA, CANLFA, PRELFA, TOTLFA
  ) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
  )
`;

export const UPDATE_INVOICE_STATUS_QUERY = `
  UPDATE F_FAC 
  SET ESTFAC = ? 
  WHERE TIPFAC = ? AND CODFAC = ?
`;

export const DELETE_TEST_INVOICE_QUERY = `
  DELETE FROM F_FAC WHERE TIPFAC = ? AND CODFAC = ?
`;

export const DELETE_TEST_INVOICE_LINES_QUERY = `
  DELETE FROM F_LFA WHERE TIPLFA = ? AND CODLFA = ?
`;
